import { ArrowRight, Clock3, MapPin, MessageCircle, Plus, Search, SlidersHorizontal, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { formatMoney } from '@/helpers/currency';
import { useDemoStore } from '@/services/platform/demoStore';
import { EmptyState } from '@/ui/reusables/EmptyState/EmptyState';
import { StatusBadge } from '@/ui/reusables/StatusBadge/StatusBadge';

const friendlyTimeline = { ASAP: 'Ready to decide', 'Within 1 week': 'Deciding this week', 'Within 2 weeks': 'Deciding in 2–4 weeks', 'Just exploring': 'Researching options' } as const;

export default function DealerListScreen() {
  const path = useLocation().pathname;
  const session = useDemoStore((state) => state.session);
  const requests = useDemoStore((state) => state.requests);
  const quotes = useDemoStore((state) => state.quotes);
  const [search, setSearch] = useState('');
  const [distance, setDistance] = useState('50');
  if (path === '/feed') return <Feed />;
  const dealsOnly = path === '/deals' || path === '/orders';
  const mine = quotes.filter((quote) => dealsOnly ? quote.status === 'accepted' : quote.dealerId === session?.id);
  return <div className="shell page-content"><div className="page-heading"><div><span className="eyebrow">{dealsOnly ? session?.role === 'buyer' ? 'Your orders' : 'Won business' : 'Dealer quotes'}</span><h1>{dealsOnly ? session?.role === 'buyer' ? 'Orders moving forward' : 'Deals in progress' : 'Your active offers'}</h1><p>{dealsOnly ? 'Track the accepted quote through paperwork, funding, dispatch, and delivery.' : 'Monitor your position, expiry, and open conversations from one place.'}</p></div>{!dealsOnly && <Link className="button button-primary" to="/feed"><Plus size={17} /> Find buyer demand</Link>}</div><section className="card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Vehicle request</th><th>{session?.role === 'buyer' ? 'Dealer' : 'Buyer area'}</th><th>Out-the-door</th><th>Status</th><th>Conversation</th><th /></tr></thead><tbody>{mine.map((quote) => { const request = requests.find((item) => item.id === quote.requestId); return <tr key={quote.id}><td><strong>{request?.brand} {request?.model}</strong><small>{request?.yearMin}–{request?.yearMax} · {request?.bodyType}</small></td><td>{session?.role === 'buyer' ? quote.dealerName : <span><MapPin size={13} /> {request?.area} · approx. 12 mi</span>}</td><td><strong className="price">{formatMoney(quote.finalPrice)}</strong></td><td><StatusBadge status={dealsOnly ? quote.dealStatus ?? quote.status : quote.status} /></td><td>{quote.contactAvailable ? <Link to={`/chat/${quote.id}`} className="button button-secondary button-sm"><MessageCircle size={15} /> Open chat</Link> : quote.chatRequestStatus === 'pending' ? <Link to="/chat/requests" className="button button-secondary button-sm"><Clock3 size={15} /> Buyer waiting</Link> : <span className="muted">Not opened</span>}</td><td><Link className="button button-ghost button-sm" to={dealsOnly ? `/${session?.role === 'buyer' ? 'orders' : 'deals'}/${quote.id}` : `/quotes/${quote.id}`}>View <ArrowRight size={15} /></Link></td></tr>; })}</tbody></table></div>{mine.length === 0 && <EmptyState title={dealsOnly ? 'No accepted deals yet' : 'No quotes yet'} description={dealsOnly ? 'Accepted offers will appear here for fulfillment tracking.' : 'Open the buyer feed to send your first quote.'} />}</section></div>;

  function Feed() {
    const feed = requests.filter((request) => request.status === 'open').filter((request) => request.radiusMiles <= Number(distance) || Number(distance) === 250).filter((request) => `${request.brand} ${request.model} ${request.area}`.toLowerCase().includes(search.toLowerCase()));
    return <div className="shell page-content"><div className="page-heading"><div><span className="eyebrow">Verified buyer demand</span><h1>Quote the requests you can win.</h1><p>Buyer identity stays private. Match on vehicle fit, approximate distance, timing, and your ability to deliver.</p></div><span className="live-ops"><i /> {feed.length} live matches</span></div><div className="card card-pad list-toolbar"><label className="search-field"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search brand, model, or area" /></label><label className="select-inline"><SlidersHorizontal size={16} /><select value={distance} onChange={(event) => setDistance(event.target.value)} aria-label="Maximum distance"><option value="25">Within 25 miles</option><option value="50">Within 50 miles</option><option value="100">Within 100 miles</option><option value="250">All matched areas</option></select></label></div><div className="grid grid-3 dealer-feed">{feed.map((request, index) => <article className="card card-hover demand-card" key={request.id}><div className="demand-card-accent"><span>{request.brand.slice(0, 1)}{request.model.slice(0, 1)}</span><StatusBadge status="live" /></div><div className="card-pad"><span className="eyebrow">{friendlyTimeline[request.timeline]}</span><h3>{request.brand} {request.model}</h3><div className="demand-meta"><span><MapPin size={14} /> {request.area} · approx. {8 + index * 7} mi</span><span><Clock3 size={14} /> Posted {index + 1}h ago</span></div><div className="request-tags">{request.mustHaves.slice(0, 3).map((item) => <span className="status status-draft" key={item}>{item}</span>)}</div><div className="demand-fit"><Sparkles size={15} /><span><strong>{92 - index * 4}% match</strong><small>{request.yearMin}–{request.yearMax} · {request.bodyType}</small></span></div><Link className="button button-primary button-wide" to={`/feed/${request.id}`}>Review brief & quote <ArrowRight size={16} /></Link></div></article>)}</div>{feed.length === 0 && <div className="card"><EmptyState title="No matches found" description="Expand your distance or clear the search." /></div>}</div>;
  }
}
